[[language]]
name = "bash"
file-types = ["bashrc"]
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "python"
scope = "source.python"
roots = [".", "pyproject.toml"]
language-servers = ["ruff", "pyright"]
auto-format = false
indent = { tab-width = 4, unit = "    " }

[language-server.ruff]
command = "ruff-lsp"

[language-server-ruff.config]
settins = {args = []}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true


[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"
